// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DebugEnvApiV1DebugEnvGetData, DebugEnvApiV1DebugEnvGetResponses, ListAssetsApiV1AssetsGetData, ListAssetsApiV1AssetsGetResponses, ListDatasetsApiV1DatasetsGetData, ListDatasetsApiV1DatasetsGetErrors, ListDatasetsApiV1DatasetsGetResponses, ListJobsApiV1JobsGetData, ListJobsApiV1JobsGetResponses, ListProjectsApiV1ProjectsGetData, ListProjectsApiV1ProjectsGetResponses, LoginApiV1AuthLoginPostData, LoginApiV1AuthLoginPostErrors, LoginApiV1AuthLoginPostResponses, MeApiV1AuthMeGetData, MeApiV1AuthMeGetResponses, RefreshApiV1AuthRefreshPostData, RefreshApiV1AuthRefreshPostErrors, RefreshApiV1AuthRefreshPostResponses, RegisterApiV1AuthRegisterPostData, RegisterApiV1AuthRegisterPostErrors, RegisterApiV1AuthRegisterPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Register a new user
 */
export const registerApiV1AuthRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterApiV1AuthRegisterPostData, ThrowOnError>) => {
    return (options.client ?? client).post<RegisterApiV1AuthRegisterPostResponses, RegisterApiV1AuthRegisterPostErrors, ThrowOnError>({
        url: '/api/v1/auth/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * User login
 */
export const loginApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiV1AuthLoginPostData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginApiV1AuthLoginPostResponses, LoginApiV1AuthLoginPostErrors, ThrowOnError>({
        url: '/api/v1/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Refresh
 */
export const refreshApiV1AuthRefreshPost = <ThrowOnError extends boolean = false>(options: Options<RefreshApiV1AuthRefreshPostData, ThrowOnError>) => {
    return (options.client ?? client).post<RefreshApiV1AuthRefreshPostResponses, RefreshApiV1AuthRefreshPostErrors, ThrowOnError>({
        url: '/api/v1/auth/refresh',
        ...options
    });
};

/**
 * Me
 */
export const meApiV1AuthMeGet = <ThrowOnError extends boolean = false>(options?: Options<MeApiV1AuthMeGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<MeApiV1AuthMeGetResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/auth/me',
        ...options
    });
};

/**
 * List projects for the current user
 *
 * List projects for the current user/tenant.
 */
export const listProjectsApiV1ProjectsGet = <ThrowOnError extends boolean = false>(options?: Options<ListProjectsApiV1ProjectsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListProjectsApiV1ProjectsGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/projects/',
        ...options
    });
};

/**
 * List datasets for a project
 *
 * List datasets belonging to the given project.
 */
export const listDatasetsApiV1DatasetsGet = <ThrowOnError extends boolean = false>(options: Options<ListDatasetsApiV1DatasetsGetData, ThrowOnError>) => {
    return (options.client ?? client).get<ListDatasetsApiV1DatasetsGetResponses, ListDatasetsApiV1DatasetsGetErrors, ThrowOnError>({
        url: '/api/v1/datasets/',
        ...options
    });
};

/**
 * List Assets
 *
 * TODO: List assets for a dataset.
 */
export const listAssetsApiV1AssetsGet = <ThrowOnError extends boolean = false>(options?: Options<ListAssetsApiV1AssetsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListAssetsApiV1AssetsGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/assets/',
        ...options
    });
};

/**
 * List Jobs
 *
 * TODO: List jobs.
 */
export const listJobsApiV1JobsGet = <ThrowOnError extends boolean = false>(options?: Options<ListJobsApiV1JobsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListJobsApiV1JobsGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/jobs/',
        ...options
    });
};

/**
 * Debug Env
 *
 * Return the current environment settings for debugging purposes.
 */
export const debugEnvApiV1DebugEnvGet = <ThrowOnError extends boolean = false>(options?: Options<DebugEnvApiV1DebugEnvGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<DebugEnvApiV1DebugEnvGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/debug/env',
        ...options
    });
};
